Update pathlib.md
GraiaCommunity/Docs pull request #92
Opened 2023-07-30 20:10 UTC by Hamusuta0320

对文件分割符解释有误，作出修改

2023-07-30 23:42 UTC, Redlnn requested changes

2023-07-30 23:42 UTC, Redlnn commented on docs/other/pathlib.md
> +- 在 Windows 上，分隔符是正斜杠 `\`, 代码中一般表示为`some_path = 'C:\\xxx\xxx.txt'`，需要对反斜杠进行转义
建议改为：在 Windows 上，分隔符是正斜杠 `\`，代码中使用时需要对其进行转义，即`some_path = "C:\\xxx\\xxx.txt"`

2023-07-30 23:42 UTC, Redlnn commented on docs/other/pathlib.md
> +- 在 Linux 上，分隔符是反斜杠 `/`，代码中一般表示为`some_path = '/home/xxx/xxx.txt'`
建议改为：在 Linux/macOS 上，分隔符是反斜杠 `/`，例如 `some_path = "/home/xxx/xxx.txt"`

2023-07-30 23:53 UTC, Hamusuta0320 commented on docs/other/pathlib.md
> +- 在 Windows 上，分隔符是正斜杠 `\`, 代码中一般表示为`some_path = 'C:\\xxx\xxx.txt'`，需要对反斜杠进行转义
好的，改好了

2023-07-31 00:14 UTC, Redlnn requested changes

2023-07-31 00:14 UTC, Redlnn commented on docs/other/pathlib.md
> +- 在 Linux/MacOS 上，分隔符是正斜杠 `/`，例如 `some_path = "/home/xxx/xxx.txt"`
![Screenshot_2023-07-31-08-01-25-472_com.microsoft.emmx.png](https://github.com/GraiaCommunity/Docs/assets/41742767/99994c5e-38d6-40fc-9c91-72b85edd358b)

应为 `macOS`

2023-08-01 14:12 UTC, Redlnn approved these changes

2023-08-01 14:13 UTC, Redlnn approved these changes

2023-08-01 14:13 UTC, merged